name: mouse
description: Simple mouse control for Dart using FFI, for desktop platforms.
version: 1.0.0
repository: https://github.com/kikuchy/mouse

environment:
  sdk: ^3.5.4

platforms:
  windows:
  macos:

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.3
  objective_c: ^7.1.0
  win32: ^5.10.1

dev_dependencies:
  ffigen: ^18.1.0
  lints: ^4.0.0
  test: ^1.24.0

ffigen:
  name: CoreGraphics
  description: Bindings for CoreGraphics.
  language: objc
  output: 'lib/src/macos/core_graphics_bindings.dart'
  headers:
    entry-points:
      - '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CoreGraphics.h'
