name: mouse
description: Simple mouse control for Dart using FFI, for desktop platforms.
version: 1.0.1+1
repository: https://github.com/kikuchy/mouse

environment:
  sdk: ^3.5.4

platforms:
  windows:
  macos:
  linux:

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.3
  win32: ^5.10.1

dev_dependencies:
  ffigen: ^18.1.0
  lints: ^4.0.0
  test: ^1.24.0
      